services:
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pipeline_network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=avgCalResults
      - MYSQL_ROOT_PASSWORD=mysql1234
    ports:
      - "3307:3306"
    networks:
      - pipeline_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pmysql1234"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --- MONITORING TOOLS ---
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pipeline_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - pipeline_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - pipeline_network

networks:
  pipeline_network: